// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: services/kss/v1/kss_service.proto

package kssv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KnowledgeStorageService_GetSuggestedNodesAndLinks_FullMethodName = "/kss.v1.KnowledgeStorageService/GetSuggestedNodesAndLinks"
)

// KnowledgeStorageServiceClient is the client API for KnowledgeStorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Knowledge Storage Service (KSS) is responsible for managing and retrieving knowledge nodes and links.
type KnowledgeStorageServiceClient interface {
	// Returns similar nodes and current links based on transcript and naive nodes
	GetSuggestedNodesAndLinks(ctx context.Context, in *KSSRequest, opts ...grpc.CallOption) (*KSSResponse, error)
}

type knowledgeStorageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKnowledgeStorageServiceClient(cc grpc.ClientConnInterface) KnowledgeStorageServiceClient {
	return &knowledgeStorageServiceClient{cc}
}

func (c *knowledgeStorageServiceClient) GetSuggestedNodesAndLinks(ctx context.Context, in *KSSRequest, opts ...grpc.CallOption) (*KSSResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KSSResponse)
	err := c.cc.Invoke(ctx, KnowledgeStorageService_GetSuggestedNodesAndLinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KnowledgeStorageServiceServer is the server API for KnowledgeStorageService service.
// All implementations must embed UnimplementedKnowledgeStorageServiceServer
// for forward compatibility.
//
// Knowledge Storage Service (KSS) is responsible for managing and retrieving knowledge nodes and links.
type KnowledgeStorageServiceServer interface {
	// Returns similar nodes and current links based on transcript and naive nodes
	GetSuggestedNodesAndLinks(context.Context, *KSSRequest) (*KSSResponse, error)
	mustEmbedUnimplementedKnowledgeStorageServiceServer()
}

// UnimplementedKnowledgeStorageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKnowledgeStorageServiceServer struct{}

func (UnimplementedKnowledgeStorageServiceServer) GetSuggestedNodesAndLinks(context.Context, *KSSRequest) (*KSSResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSuggestedNodesAndLinks not implemented")
}
func (UnimplementedKnowledgeStorageServiceServer) mustEmbedUnimplementedKnowledgeStorageServiceServer() {
}
func (UnimplementedKnowledgeStorageServiceServer) testEmbeddedByValue() {}

// UnsafeKnowledgeStorageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KnowledgeStorageServiceServer will
// result in compilation errors.
type UnsafeKnowledgeStorageServiceServer interface {
	mustEmbedUnimplementedKnowledgeStorageServiceServer()
}

func RegisterKnowledgeStorageServiceServer(s grpc.ServiceRegistrar, srv KnowledgeStorageServiceServer) {
	// If the following call pancis, it indicates UnimplementedKnowledgeStorageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KnowledgeStorageService_ServiceDesc, srv)
}

func _KnowledgeStorageService_GetSuggestedNodesAndLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KSSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeStorageServiceServer).GetSuggestedNodesAndLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeStorageService_GetSuggestedNodesAndLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeStorageServiceServer).GetSuggestedNodesAndLinks(ctx, req.(*KSSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KnowledgeStorageService_ServiceDesc is the grpc.ServiceDesc for KnowledgeStorageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KnowledgeStorageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kss.v1.KnowledgeStorageService",
	HandlerType: (*KnowledgeStorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSuggestedNodesAndLinks",
			Handler:    _KnowledgeStorageService_GetSuggestedNodesAndLinks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/kss/v1/kss_service.proto",
}
